version: 2

sources:
  - name: STAGE
    description: This is SOURCE for STAGE
    database: DBT_TRAINING_MR
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
  - name: RAW
    description: This is SOURCE for STAGE
    database: DBT_TRAINING_MR
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
      - name: V_CUSTOMER
      - name: V_ORDERS
      - name: V_LINEITEM
      - name: V_NATION